### PR TITLE
Add postgresql support

### PR DESCRIPTION
**Pull request by toniiiik**
**Description of the change**

- add postgresql client nami package
- update jasperreports nami package helper and package descriptor (new input paramter)
- change environment variables

**Benefits**
- support for postgresql database

**Possible drawbacks**
- backward compatibility... It is required to set original ENV for mariadb and jasper connection

**Applicable issues**
#63 

**Additional information**
- it will be nice to fix some parts in root packages not in dockerfile (jasperreports nami, postgresql-client add executeSqlFiles, etc.)

### CODE REVIEW

**Review by miguelaeh — COMMENTED** [review]
Hi @toniiik ,
Thank you very much for the work you have done here!!!
I am afraid we are in the middle of a process to move jasperreports logic to bash, so we cannot accept this change right now, nevertheless, we will add the support for postgresql once we finish the migration of the logic.

**Comment by toniiiik** [comment]
> Hi @toniiik ,
> Thank you very much for the work you have done here!!!
> I am afraid we are in the middle of a process to move jasperreports logic to bash, so we cannot accept this change right now, nevertheless, we will add the support for postgresql once we finish the migration of the logic.

Thank you @miguelaeh for information. Considering the fact of "migration" logic I thing we can close this PR. When do you plan finish the process of moving to bash?

**Comment by marcosbc** [comment]
@toniiiik Unfortunately we don't have a precise ETA due to summer holidays, but Jasper Reports is in fact the next in the list of container images for which we are going to refactor the initialization logic and open-source it into the `rootfs` folder. We will keep you posted in this PR.

**Comment by jeffreyvdhondel** [comment]
Is there a ETA for this?

**Pull request closed without merging**
